/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mphpayroll;

import java.util.HashSet;
import java.util.Set;
import com.mycompany.mphpayroll.Login;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author AXISMEG
 */
public class empadmin extends javax.swing.JFrame {

    
    public empadmin() {
        initComponents();

    }
    
    empadmin(String empID) {
        initComponents();
        
        lbl_logemp.setText("Employee No. " + empID);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_logemp = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jb_appmanagement = new javax.swing.JButton();
        jb_empsearch = new javax.swing.JButton();
        jb_empreg = new javax.swing.JButton();
        jb_empupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbl_logemp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_logemp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logemp.setText("Employee No.");
        getContentPane().add(lbl_logemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + ("\\src\\main\\java\\com\\mycompany\\mphpayroll\\Images\\pbutton.png")));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 60, 60));

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EMPLOYEE LIST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 190, 50));

        jb_appmanagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_appmanagement.setText("APP MANAGEMENT");
        jb_appmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_appmanagementActionPerformed(evt);
            }
        });
        getContentPane().add(jb_appmanagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 190, 50));

        jb_empsearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_empsearch.setText("EMPLOYEE SEARCH");
        jb_empsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_empsearchActionPerformed(evt);
            }
        });
        getContentPane().add(jb_empsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 190, 50));

        jb_empreg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_empreg.setText("EMPLOYEE REGISTRATION");
        jb_empreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_empregActionPerformed(evt);
            }
        });
        getContentPane().add(jb_empreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 190, 50));

        jb_empupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jb_empupdate.setText("INFORMATION UPDATE");
        jb_empupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_empupdateActionPerformed(evt);
            }
        });
        getContentPane().add(jb_empupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ ("\\src\\main\\java\\com\\mycompany\\mphpayroll\\Images\\bgmain.png")));
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_empregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_empregActionPerformed
        
        empreg nextForm1 = new empreg();
        nextForm1.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jb_empregActionPerformed

    private void jb_empsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_empsearchActionPerformed
        
        this.dispose();
        
        empsearch newForm = new empsearch();
        newForm.setVisible(true);

    }//GEN-LAST:event_jb_empsearchActionPerformed

    private void jb_appmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_appmanagementActionPerformed
       
        
        
    }//GEN-LAST:event_jb_appmanagementActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        this.dispose();
        
        Login nextForm = new Login();
        nextForm.setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jb_empupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_empupdateActionPerformed
  
        empupdate nextForm1 = new empupdate();
        nextForm1.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_jb_empupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jb_appmanagement;
    private javax.swing.JButton jb_empreg;
    private javax.swing.JButton jb_empsearch;
    private javax.swing.JButton jb_empupdate;
    private javax.swing.JLabel lbl_logemp;
    // End of variables declaration//GEN-END:variables
}
